insert into words (word) values ('core');
insert into words (word) values ('24 hour');
insert into words (word) values ('Diverse');
insert into words (word) values ('disintermediate');
insert into words (word) values ('disintermediate');
insert into words (word) values ('Programmable');
insert into words (word) values ('methodical');
insert into words (word) values ('scalable');
insert into words (word) values ('strategy');
insert into words (word) values ('Front-line');
insert into words (word) values ('Diverse');
insert into words (word) values ('architecture');
insert into words (word) values ('Cross-group');
insert into words (word) values ('Polarised');
insert into words (word) values ('internet solution');
insert into words (word) values ('multi-tasking');
insert into words (word) values ('open architecture');
insert into words (word) values ('Organic');
insert into words (word) values ('eco-centric');
insert into words (word) values ('Digitized');
insert into words (word) values ('Fully-configurable');
insert into words (word) values ('Networked');
insert into words (word) values ('empowering');
insert into words (word) values ('middleware');
insert into words (word) values ('capability');
insert into words (word) values ('Versatile');
insert into words (word) values ('maximized');
insert into words (word) values ('interactive');
insert into words (word) values ('homogeneous');
insert into words (word) values ('process improvement');
insert into words (word) values ('systematic');
insert into words (word) values ('fresh-thinking');
insert into words (word) values ('hardware');
insert into words (word) values ('leverage');
insert into words (word) values ('paradigm');
insert into words (word) values ('Balanced');
insert into words (word) values ('Streamlined');
insert into words (word) values ('Organized');
insert into words (word) values ('hybrid');
insert into words (word) values ('disintermediate');
insert into words (word) values ('throughput');
insert into words (word) values ('Secured');
insert into words (word) values ('heuristic');
insert into words (word) values ('methodical');
insert into words (word) values ('Vision-oriented');
insert into words (word) values ('Innovative');
insert into words (word) values ('Configurable');
insert into words (word) values ('pricing structure');
insert into words (word) values ('website');
insert into words (word) values ('Multi-channelled');
insert into words (word) values ('responsive');
insert into words (word) values ('functionalities');
insert into words (word) values ('Universal');
insert into words (word) values ('benchmark');
insert into words (word) values ('leverage');
insert into words (word) values ('homogeneous');
insert into words (word) values ('Balanced');
insert into words (word) values ('Devolved');
insert into words (word) values ('multi-state');
insert into words (word) values ('Front-line');
insert into words (word) values ('even-keeled');
insert into words (word) values ('Graphical User Interface');
insert into words (word) values ('Progressive');
insert into words (word) values ('value-added');
insert into words (word) values ('regional');
insert into words (word) values ('modular');
insert into words (word) values ('Enterprise-wide');
insert into words (word) values ('eco-centric');
insert into words (word) values ('24 hour');
insert into words (word) values ('Seamless');
insert into words (word) values ('time-frame');
insert into words (word) values ('concept');
insert into words (word) values ('contextually-based');
insert into words (word) values ('paradigm');
insert into words (word) values ('full-range');
insert into words (word) values ('Self-enabling');
insert into words (word) values ('Adaptive');
insert into words (word) values ('help-desk');
insert into words (word) values ('methodology');
insert into words (word) values ('regional');
insert into words (word) values ('Enhanced');
insert into words (word) values ('reciprocal');
insert into words (word) values ('neural-net');
insert into words (word) values ('neural-net');
insert into words (word) values ('Customer-focused');
insert into words (word) values ('user-facing');
insert into words (word) values ('website');
insert into words (word) values ('Cross-group');
insert into words (word) values ('migration');
insert into words (word) values ('Optimized');
insert into words (word) values ('Virtual');
insert into words (word) values ('Networked');
insert into words (word) values ('reciprocal');
insert into words (word) values ('24 hour');
insert into words (word) values ('neural-net');
insert into words (word) values ('zero tolerance');
insert into words (word) values ('paradigm');
insert into words (word) values ('task-force');
insert into words (word) values ('Monitored');
insert into words (word) values ('contextually-based');
insert into words (word) values ('utilisation');
insert into words (word) values ('Distributed');
insert into words (word) values ('standardization');
insert into words (word) values ('Self-enabling');
insert into words (word) values ('ability');
insert into words (word) values ('Customer-focused');
insert into words (word) values ('Progressive');
insert into words (word) values ('Expanded');
insert into words (word) values ('benchmark');
insert into words (word) values ('Vision-oriented');
insert into words (word) values ('Virtual');
insert into words (word) values ('algorithm');
insert into words (word) values ('systematic');
insert into words (word) values ('portal');
insert into words (word) values ('time-frame');
insert into words (word) values ('multimedia');
insert into words (word) values ('Realigned');
insert into words (word) values ('website');
insert into words (word) values ('zero administration');
insert into words (word) values ('impactful');
insert into words (word) values ('Function-based');
insert into words (word) values ('Multi-channelled');
insert into words (word) values ('Mandatory');
insert into words (word) values ('Re-contextualized');
insert into words (word) values ('fault-tolerant');
insert into words (word) values ('Up-sized');
insert into words (word) values ('Phased');
insert into words (word) values ('Cloned');
insert into words (word) values ('Organized');
insert into words (word) values ('demand-driven');
insert into words (word) values ('next generation');
insert into words (word) values ('functionalities');
insert into words (word) values ('cohesive');
insert into words (word) values ('Face to face');
insert into words (word) values ('5th generation');
insert into words (word) values ('impactful');
insert into words (word) values ('24/7');
insert into words (word) values ('Face to face');
insert into words (word) values ('well-modulated');
insert into words (word) values ('4th generation');
insert into words (word) values ('24/7');
insert into words (word) values ('Expanded');
insert into words (word) values ('middleware');
insert into words (word) values ('high-level');
insert into words (word) values ('methodical');
insert into words (word) values ('disintermediate');
insert into words (word) values ('protocol');
insert into words (word) values ('access');
insert into words (word) values ('Down-sized');
insert into words (word) values ('conglomeration');
insert into words (word) values ('Implemented');
insert into words (word) values ('functionalities');
insert into words (word) values ('strategy');
insert into words (word) values ('high-level');
insert into words (word) values ('Networked');
insert into words (word) values ('product');
insert into words (word) values ('Ergonomic');
insert into words (word) values ('approach');
insert into words (word) values ('Virtual');
insert into words (word) values ('Virtual');
insert into words (word) values ('methodology');
insert into words (word) values ('executive');
insert into words (word) values ('customer loyalty');
insert into words (word) values ('Horizontal');
insert into words (word) values ('groupware');
insert into words (word) values ('concept');
insert into words (word) values ('scalable');
insert into words (word) values ('Quality-focused');
insert into words (word) values ('Reduced');
insert into words (word) values ('adapter');
insert into words (word) values ('disintermediate');
insert into words (word) values ('success');
insert into words (word) values ('solution');
insert into words (word) values ('methodology');
insert into words (word) values ('content-based');
insert into words (word) values ('attitude-oriented');
insert into words (word) values ('groupware');
insert into words (word) values ('conglomeration');
insert into words (word) values ('Vision-oriented');
insert into words (word) values ('Face to face');
insert into words (word) values ('Open-architected');
insert into words (word) values ('systemic');
insert into words (word) values ('Universal');
insert into words (word) values ('holistic');
insert into words (word) values ('Graphic Interface');
insert into words (word) values ('software');
insert into words (word) values ('hybrid');
insert into words (word) values ('global');
insert into words (word) values ('throughput');
insert into words (word) values ('Proactive');
insert into words (word) values ('value-added');
insert into words (word) values ('client-driven');
insert into words (word) values ('synergy');
insert into words (word) values ('6th generation');
insert into words (word) values ('Enterprise-wide');
insert into words (word) values ('time-frame');
insert into words (word) values ('6th generation');
insert into words (word) values ('info-mediaries');
insert into words (word) values ('Customer-focused');
insert into words (word) values ('portal');
insert into words (word) values ('content-based');
insert into words (word) values ('Secured');
insert into words (word) values ('disintermediate');
insert into words (word) values ('Up-sized');
insert into words (word) values ('strategy');
insert into words (word) values ('Vision-oriented');
insert into words (word) values ('Synergistic');
insert into words (word) values ('Enterprise-wide');
insert into words (word) values ('radical');
insert into words (word) values ('encryption');
insert into words (word) values ('tertiary');
insert into words (word) values ('budgetary management');
insert into words (word) values ('Cross-group');
insert into words (word) values ('Inverse');
insert into words (word) values ('time-frame');
insert into words (word) values ('User-centric');
insert into words (word) values ('toolset');
insert into words (word) values ('Assimilated');
insert into words (word) values ('workforce');
insert into words (word) values ('Diverse');
insert into words (word) values ('needs-based');
insert into words (word) values ('User-centric');
insert into words (word) values ('orchestration');
insert into words (word) values ('global');
insert into words (word) values ('disintermediate');
insert into words (word) values ('Digitized');
insert into words (word) values ('contingency');
insert into words (word) values ('zero administration');
insert into words (word) values ('zero tolerance');
insert into words (word) values ('Configurable');
insert into words (word) values ('toolset');
insert into words (word) values ('task-force');
insert into words (word) values ('dynamic');
insert into words (word) values ('support');
insert into words (word) values ('Persistent');
insert into words (word) values ('fresh-thinking');
insert into words (word) values ('Enterprise-wide');
insert into words (word) values ('secured line');
insert into words (word) values ('object-oriented');
insert into words (word) values ('Optimized');
insert into words (word) values ('benchmark');
insert into words (word) values ('system-worthy');
insert into words (word) values ('methodology');
insert into words (word) values ('Automated');
insert into words (word) values ('Programmable');
insert into words (word) values ('Customer-focused');
insert into words (word) values ('attitude');
insert into words (word) values ('policy');
insert into words (word) values ('open system');
insert into words (word) values ('success');
insert into words (word) values ('interface');
insert into words (word) values ('Re-engineered');
insert into words (word) values ('service-desk');
insert into words (word) values ('help-desk');
insert into words (word) values ('Extended');
insert into words (word) values ('forecast');
insert into words (word) values ('Reduced');
insert into words (word) values ('Phased');
insert into words (word) values ('Customer-focused');
insert into words (word) values ('Balanced');
insert into words (word) values ('Persistent');
insert into words (word) values ('Multi-channelled');
insert into words (word) values ('open system');
insert into words (word) values ('logistical');
insert into words (word) values ('Intuitive');
insert into words (word) values ('Balanced');
insert into words (word) values ('moderator');
insert into words (word) values ('open architecture');
insert into words (word) values ('project');
insert into words (word) values ('radical');
insert into words (word) values ('static');
insert into words (word) values ('full-range');
insert into words (word) values ('algorithm');
insert into words (word) values ('Pre-emptive');
insert into words (word) values ('zero defect');
insert into words (word) values ('strategy');
insert into words (word) values ('Vision-oriented');
insert into words (word) values ('Synergized');
insert into words (word) values ('standardization');
insert into words (word) values ('Enhanced');
insert into words (word) values ('Graphical User Interface');
insert into words (word) values ('Distributed');
insert into words (word) values ('firmware');
insert into words (word) values ('Function-based');
insert into words (word) values ('hybrid');
insert into words (word) values ('artificial intelligence');
insert into words (word) values ('explicit');
insert into words (word) values ('pricing structure');
insert into words (word) values ('multi-tasking');
insert into words (word) values ('Robust');
insert into words (word) values ('bandwidth-monitored');
insert into words (word) values ('Realigned');
insert into words (word) values ('4th generation');
insert into words (word) values ('Compatible');
insert into words (word) values ('human-resource');
insert into words (word) values ('User-centric');
insert into words (word) values ('real-time');
insert into words (word) values ('Organized');
insert into words (word) values ('success');
insert into words (word) values ('Enhanced');
insert into words (word) values ('Enhanced');
insert into words (word) values ('even-keeled');
insert into words (word) values ('migration');
insert into words (word) values ('Implemented');
insert into words (word) values ('orchestration');
insert into words (word) values ('Function-based');
insert into words (word) values ('Team-oriented');
insert into words (word) values ('complexity');
insert into words (word) values ('solution-oriented');
insert into words (word) values ('zero tolerance');
insert into words (word) values ('product');
insert into words (word) values ('alliance');
insert into words (word) values ('static');
insert into words (word) values ('Reverse-engineered');
insert into words (word) values ('Graphic Interface');
insert into words (word) values ('benchmark');
insert into words (word) values ('budgetary management');
insert into words (word) values ('capacity');
insert into words (word) values ('directional');
insert into words (word) values ('Right-sized');
insert into words (word) values ('Ameliorated');
insert into words (word) values ('paradigm');
insert into words (word) values ('secondary');
insert into words (word) values ('reciprocal');
insert into words (word) values ('Business-focused');
insert into words (word) values ('Seamless');
insert into words (word) values ('access');
insert into words (word) values ('full-range');
insert into words (word) values ('Ameliorated');
insert into words (word) values ('installation');
insert into words (word) values ('conglomeration');
insert into words (word) values ('systematic');
insert into words (word) values ('secured line');
insert into words (word) values ('fresh-thinking');
insert into words (word) values ('matrix');
insert into words (word) values ('Multi-tiered');
insert into words (word) values ('Polarised');
insert into words (word) values ('Optional');
insert into words (word) values ('definition');
insert into words (word) values ('scalable');
insert into words (word) values ('Synergistic');
insert into words (word) values ('fresh-thinking');
insert into words (word) values ('initiative');
insert into words (word) values ('budgetary management');
insert into words (word) values ('client-driven');
insert into words (word) values ('installation');
insert into words (word) values ('24 hour');
insert into words (word) values ('Streamlined');
insert into words (word) values ('leading edge');
insert into words (word) values ('Horizontal');
insert into words (word) values ('disintermediate');
insert into words (word) values ('impactful');
insert into words (word) values ('moratorium');
insert into words (word) values ('superstructure');
insert into words (word) values ('benchmark');
insert into words (word) values ('transitional');
insert into words (word) values ('24 hour');
insert into words (word) values ('intermediate');
insert into words (word) values ('Configurable');
insert into words (word) values ('projection');
insert into words (word) values ('encompassing');
insert into words (word) values ('asynchronous');
insert into words (word) values ('Persistent');
insert into words (word) values ('Customizable');
insert into words (word) values ('fresh-thinking');
insert into words (word) values ('Cross-group');
insert into words (word) values ('impactful');
insert into words (word) values ('Centralized');
insert into words (word) values ('Visionary');
insert into words (word) values ('utilisation');
insert into words (word) values ('emulation');
insert into words (word) values ('Profit-focused');
insert into words (word) values ('motivating');
insert into words (word) values ('Intuitive');
insert into words (word) values ('Total');
insert into words (word) values ('Stand-alone');
insert into words (word) values ('Devolved');
insert into words (word) values ('analyzer');
insert into words (word) values ('functionalities');
insert into words (word) values ('conglomeration');
insert into words (word) values ('next generation');
insert into words (word) values ('holistic');
insert into words (word) values ('multi-tasking');
insert into words (word) values ('strategy');
insert into words (word) values ('Ergonomic');
insert into words (word) values ('didactic');
insert into words (word) values ('Object-based');
insert into words (word) values ('executive');
insert into words (word) values ('firmware');
insert into words (word) values ('Open-architected');
insert into words (word) values ('extranet');
insert into words (word) values ('Persistent');
insert into words (word) values ('even-keeled');
insert into words (word) values ('Organic');
insert into words (word) values ('Inverse');
insert into words (word) values ('installation');
insert into words (word) values ('Optional');
insert into words (word) values ('help-desk');
insert into words (word) values ('Grass-roots');
insert into words (word) values ('leading edge');
insert into words (word) values ('attitude');
insert into words (word) values ('background');
insert into words (word) values ('client-server');
insert into words (word) values ('Function-based');
insert into words (word) values ('Streamlined');
insert into words (word) values ('Advanced');
insert into words (word) values ('moratorium');
insert into words (word) values ('Reduced');
insert into words (word) values ('Focused');
insert into words (word) values ('stable');
insert into words (word) values ('analyzing');
insert into words (word) values ('asynchronous');
insert into words (word) values ('instruction set');
insert into words (word) values ('throughput');
insert into words (word) values ('Multi-tiered');
insert into words (word) values ('disintermediate');
insert into words (word) values ('impactful');
insert into words (word) values ('time-frame');
insert into words (word) values ('Organized');
insert into words (word) values ('Triple-buffered');
insert into words (word) values ('hub');
insert into words (word) values ('Multi-layered');
insert into words (word) values ('toolset');
insert into words (word) values ('customer loyalty');
insert into words (word) values ('systematic');
insert into words (word) values ('Organized');
insert into words (word) values ('internet solution');
insert into words (word) values ('Face to face');
insert into words (word) values ('mission-critical');
insert into words (word) values ('standardization');
insert into words (word) values ('Graphical User Interface');
insert into words (word) values ('Face to face');
insert into words (word) values ('knowledge user');
insert into words (word) values ('discrete');
insert into words (word) values ('Advanced');
insert into words (word) values ('Face to face');
insert into words (word) values ('demand-driven');
insert into words (word) values ('uniform');
insert into words (word) values ('fresh-thinking');
insert into words (word) values ('empowering');
insert into words (word) values ('Inverse');
insert into words (word) values ('bandwidth-monitored');
insert into words (word) values ('systematic');
insert into words (word) values ('customer loyalty');
insert into words (word) values ('bifurcated');
insert into words (word) values ('adapter');
insert into words (word) values ('modular');
insert into words (word) values ('homogeneous');
insert into words (word) values ('Inverse');
insert into words (word) values ('bottom-line');
insert into words (word) values ('zero defect');
insert into words (word) values ('Extended');
insert into words (word) values ('grid-enabled');
insert into words (word) values ('Virtual');
insert into words (word) values ('database');
insert into words (word) values ('radical');
insert into words (word) values ('Re-contextualized');
insert into words (word) values ('flexibility');
insert into words (word) values ('dynamic');
insert into words (word) values ('ability');
insert into words (word) values ('knowledge user');
insert into words (word) values ('local');
insert into words (word) values ('info-mediaries');
insert into words (word) values ('holistic');
insert into words (word) values ('encryption');
insert into words (word) values ('contextually-based');
insert into words (word) values ('Reverse-engineered');
insert into words (word) values ('holistic');
insert into words (word) values ('knowledge user');
insert into words (word) values ('methodical');
insert into words (word) values ('content-based');
insert into words (word) values ('Self-enabling');
insert into words (word) values ('Reverse-engineered');
insert into words (word) values ('regional');
insert into words (word) values ('software');
insert into words (word) values ('Reverse-engineered');
insert into words (word) values ('Inverse');
insert into words (word) values ('zero tolerance');
insert into words (word) values ('Secured');
insert into words (word) values ('cohesive');
insert into words (word) values ('Digitized');
insert into words (word) values ('Virtual');
insert into words (word) values ('frame');
insert into words (word) values ('implementation');
insert into words (word) values ('Stand-alone');
insert into words (word) values ('extranet');
insert into words (word) values ('matrix');
insert into words (word) values ('database');
insert into words (word) values ('empowering');
insert into words (word) values ('Synergized');
insert into words (word) values ('motivating');
insert into words (word) values ('Multi-lateral');
insert into words (word) values ('info-mediaries');
insert into words (word) values ('support');
insert into words (word) values ('Switchable');
insert into words (word) values ('asymmetric');
insert into words (word) values ('knowledge user');
insert into words (word) values ('Graphical User Interface');
insert into words (word) values ('open system');
insert into words (word) values ('User-centric');
insert into words (word) values ('flexibility');
insert into words (word) values ('responsive');
insert into words (word) values ('directional');
insert into words (word) values ('Open-architected');
insert into words (word) values ('Networked');
insert into words (word) values ('upward-trending');
insert into words (word) values ('encompassing');
insert into words (word) values ('web-enabled');
insert into words (word) values ('policy');
insert into words (word) values ('attitude');
insert into words (word) values ('scalable');
insert into words (word) values ('Multi-layered');
insert into words (word) values ('5th generation');
insert into words (word) values ('coherent');
insert into words (word) values ('Focused');
insert into words (word) values ('Networked');
insert into words (word) values ('neutral');
insert into words (word) values ('workforce');
insert into words (word) values ('Streamlined');
insert into words (word) values ('hierarchy');
insert into words (word) values ('actuating');
insert into words (word) values ('Re-contextualized');
insert into words (word) values ('Persistent');
insert into words (word) values ('full-range');
insert into words (word) values ('superstructure');
insert into words (word) values ('complexity');
insert into words (word) values ('Object-based');
insert into words (word) values ('Universal');
insert into words (word) values ('modular');
insert into words (word) values ('Exclusive');
insert into words (word) values ('Enhanced');
insert into words (word) values ('holistic');
insert into words (word) values ('interface');
insert into words (word) values ('24/7');
insert into words (word) values ('optimal');
insert into words (word) values ('User-friendly');
insert into words (word) values ('hybrid');
insert into words (word) values ('monitoring');
insert into words (word) values ('success');
insert into words (word) values ('Enterprise-wide');
insert into words (word) values ('Decentralized');
insert into words (word) values ('local');
insert into words (word) values ('capability');
insert into words (word) values ('architecture');
insert into words (word) values ('Proactive');
insert into words (word) values ('client-driven');
insert into words (word) values ('Business-focused');
insert into words (word) values ('Digitized');
insert into words (word) values ('Optional');
insert into words (word) values ('Profit-focused');
insert into words (word) values ('analyzer');
insert into words (word) values ('dynamic');
insert into words (word) values ('adapter');
insert into words (word) values ('intermediate');
insert into words (word) values ('Cloned');
insert into words (word) values ('Up-sized');
insert into words (word) values ('dedicated');
insert into words (word) values ('Operative');
insert into words (word) values ('web-enabled');
insert into words (word) values ('asymmetric');
insert into words (word) values ('discrete');
insert into words (word) values ('object-oriented');
insert into words (word) values ('toolset');
insert into words (word) values ('Synergistic');
insert into words (word) values ('Organic');
insert into words (word) values ('service-desk');
insert into words (word) values ('ability');
insert into words (word) values ('alliance');
insert into words (word) values ('Upgradable');
insert into words (word) values ('definition');
insert into words (word) values ('neutral');
insert into words (word) values ('implementation');
insert into words (word) values ('Focused');
insert into words (word) values ('definition');
insert into words (word) values ('Multi-lateral');
insert into words (word) values ('Fundamental');
insert into words (word) values ('Automated');
insert into words (word) values ('protocol');
insert into words (word) values ('Programmable');
insert into words (word) values ('Upgradable');
insert into words (word) values ('encoding');
insert into words (word) values ('moderator');
insert into words (word) values ('encoding');
insert into words (word) values ('groupware');
insert into words (word) values ('methodical');
insert into words (word) values ('4th generation');
insert into words (word) values ('concept');
insert into words (word) values ('intranet');
insert into words (word) values ('Multi-tiered');
insert into words (word) values ('superstructure');
insert into words (word) values ('Open-source');
insert into words (word) values ('Progressive');
insert into words (word) values ('Virtual');
insert into words (word) values ('function');
insert into words (word) values ('local');
insert into words (word) values ('coherent');
insert into words (word) values ('budgetary management');
insert into words (word) values ('extranet');
insert into words (word) values ('executive');
insert into words (word) values ('help-desk');
insert into words (word) values ('Down-sized');
insert into words (word) values ('Public-key');
insert into words (word) values ('firmware');
insert into words (word) values ('needs-based');
insert into words (word) values ('holistic');
insert into words (word) values ('Graphical User Interface');
insert into words (word) values ('local area network');
insert into words (word) values ('middleware');
insert into words (word) values ('strategy');
insert into words (word) values ('hybrid');
insert into words (word) values ('model');
insert into words (word) values ('support');
insert into words (word) values ('budgetary management');
insert into words (word) values ('strategy');
insert into words (word) values ('Fully-configurable');
insert into words (word) values ('multimedia');
insert into words (word) values ('internet solution');
insert into words (word) values ('portal');
insert into words (word) values ('Graphic Interface');
insert into words (word) values ('local area network');
insert into words (word) values ('Horizontal');
insert into words (word) values ('systematic');
insert into words (word) values ('Polarised');
insert into words (word) values ('encoding');
insert into words (word) values ('monitoring');
insert into words (word) values ('forecast');
insert into words (word) values ('website');
insert into words (word) values ('time-frame');
insert into words (word) values ('Streamlined');
insert into words (word) values ('full-range');
insert into words (word) values ('extranet');
insert into words (word) values ('parallelism');
insert into words (word) values ('Digitized');
insert into words (word) values ('help-desk');
insert into words (word) values ('solution-oriented');
insert into words (word) values ('Persistent');
insert into words (word) values ('encoding');
insert into words (word) values ('Optimized');
insert into words (word) values ('toolset');
insert into words (word) values ('policy');
insert into words (word) values ('mission-critical');
insert into words (word) values ('Function-based');
insert into words (word) values ('well-modulated');
insert into words (word) values ('content-based');
insert into words (word) values ('Up-sized');
insert into words (word) values ('customer loyalty');
insert into words (word) values ('project');
insert into words (word) values ('Implemented');
insert into words (word) values ('success');
insert into words (word) values ('Customer-focused');
insert into words (word) values ('contextually-based');
insert into words (word) values ('intermediate');
insert into words (word) values ('policy');
insert into words (word) values ('installation');
insert into words (word) values ('Universal');
insert into words (word) values ('modular');
insert into words (word) values ('adapter');
insert into words (word) values ('methodical');
insert into words (word) values ('systematic');
insert into words (word) values ('stable');
insert into words (word) values ('definition');
insert into words (word) values ('incremental');
insert into words (word) values ('Vision-oriented');
insert into words (word) values ('cohesive');
insert into words (word) values ('User-friendly');
insert into words (word) values ('Seamless');
insert into words (word) values ('client-server');
insert into words (word) values ('frame');
insert into words (word) values ('Enterprise-wide');
insert into words (word) values ('intranet');
insert into words (word) values ('parallelism');
insert into words (word) values ('ability');
insert into words (word) values ('service-desk');
insert into words (word) values ('Programmable');
insert into words (word) values ('zero administration');
insert into words (word) values ('content-based');
insert into words (word) values ('Expanded');
insert into words (word) values ('6th generation');
insert into words (word) values ('algorithm');
insert into words (word) values ('open architecture');
insert into words (word) values ('systematic');
insert into words (word) values ('Synergized');
insert into words (word) values ('tangible');
insert into words (word) values ('heuristic');
insert into words (word) values ('Optimized');
insert into words (word) values ('user-facing');
insert into words (word) values ('fault-tolerant');
insert into words (word) values ('Grass-roots');
insert into words (word) values ('internet solution');
insert into words (word) values ('Future-proofed');
insert into words (word) values ('24 hour');
insert into words (word) values ('system-worthy');
insert into words (word) values ('cohesive');
insert into words (word) values ('Self-enabling');
insert into words (word) values ('Seamless');
insert into words (word) values ('Monitored');
insert into words (word) values ('user-facing');
insert into words (word) values ('actuating');
insert into words (word) values ('array');
insert into words (word) values ('initiative');
insert into words (word) values ('upward-trending');
insert into words (word) values ('Multi-tiered');
insert into words (word) values ('internet solution');
insert into words (word) values ('multimedia');
insert into words (word) values ('bi-directional');
insert into words (word) values ('Streamlined');
insert into words (word) values ('model');
insert into words (word) values ('array');
insert into words (word) values ('emulation');
insert into words (word) values ('contingency');
insert into words (word) values ('multimedia');
insert into words (word) values ('complexity');
insert into words (word) values ('leverage');
insert into words (word) values ('3rd generation');
insert into words (word) values ('client-driven');
insert into words (word) values ('strategy');
insert into words (word) values ('monitoring');
insert into words (word) values ('Future-proofed');
insert into words (word) values ('mobile');
insert into words (word) values ('Monitored');
insert into words (word) values ('executive');
insert into words (word) values ('impactful');
insert into words (word) values ('service-desk');
insert into words (word) values ('Seamless');
insert into words (word) values ('Quality-focused');
insert into words (word) values ('Organic');
insert into words (word) values ('Diverse');
insert into words (word) values ('responsive');
insert into words (word) values ('conglomeration');
insert into words (word) values ('asynchronous');
insert into words (word) values ('upward-trending');
insert into words (word) values ('moratorium');
insert into words (word) values ('analyzer');
insert into words (word) values ('contingency');
insert into words (word) values ('model');
insert into words (word) values ('Streamlined');
insert into words (word) values ('policy');
insert into words (word) values ('groupware');
insert into words (word) values ('maximized');
insert into words (word) values ('definition');
insert into words (word) values ('Intuitive');
insert into words (word) values ('Organic');
insert into words (word) values ('even-keeled');
insert into words (word) values ('contextually-based');
insert into words (word) values ('Total');
insert into words (word) values ('Customer-focused');
insert into words (word) values ('demand-driven');
insert into words (word) values ('extranet');
insert into words (word) values ('Adaptive');
insert into words (word) values ('explicit');
insert into words (word) values ('Graphical User Interface');
insert into words (word) values ('upward-trending');
insert into words (word) values ('Decentralized');
insert into words (word) values ('system-worthy');
insert into words (word) values ('Digitized');
insert into words (word) values ('reciprocal');
insert into words (word) values ('Expanded');
insert into words (word) values ('moratorium');
insert into words (word) values ('24/7');
insert into words (word) values ('analyzer');
insert into words (word) values ('parallelism');
insert into words (word) values ('structure');
insert into words (word) values ('productivity');
insert into words (word) values ('attitude');
insert into words (word) values ('Enterprise-wide');
insert into words (word) values ('system engine');
insert into words (word) values ('uniform');
insert into words (word) values ('Grass-roots');
insert into words (word) values ('Reactive');
insert into words (word) values ('functionalities');
insert into words (word) values ('Cloned');
insert into words (word) values ('motivating');
insert into words (word) values ('motivating');
insert into words (word) values ('Innovative');
insert into words (word) values ('migration');
insert into words (word) values ('regional');
insert into words (word) values ('encoding');
insert into words (word) values ('Front-line');
insert into words (word) values ('high-level');
insert into words (word) values ('local area network');
insert into words (word) values ('demand-driven');
insert into words (word) values ('content-based');
insert into words (word) values ('system engine');
insert into words (word) values ('responsive');
insert into words (word) values ('content-based');
insert into words (word) values ('superstructure');
insert into words (word) values ('utilisation');
insert into words (word) values ('systematic');
insert into words (word) values ('Managed');
insert into words (word) values ('orchestration');
insert into words (word) values ('budgetary management');
insert into words (word) values ('hardware');
insert into words (word) values ('User-friendly');
insert into words (word) values ('responsive');
insert into words (word) values ('even-keeled');
insert into words (word) values ('orchestration');
insert into words (word) values ('pricing structure');
insert into words (word) values ('product');
insert into words (word) values ('Graphic Interface');
insert into words (word) values ('functionalities');
insert into words (word) values ('open system');
insert into words (word) values ('background');
insert into words (word) values ('methodical');
insert into words (word) values ('help-desk');
insert into words (word) values ('Grass-roots');
insert into words (word) values ('moratorium');
insert into words (word) values ('leverage');
insert into words (word) values ('Cloned');
insert into words (word) values ('Balanced');
insert into words (word) values ('Ameliorated');
insert into words (word) values ('Upgradable');
insert into words (word) values ('fault-tolerant');
insert into words (word) values ('even-keeled');
insert into words (word) values ('superstructure');
insert into words (word) values ('open system');
insert into words (word) values ('systemic');
insert into words (word) values ('interface');
insert into words (word) values ('Programmable');
insert into words (word) values ('Inverse');
insert into words (word) values ('executive');
insert into words (word) values ('Sharable');
insert into words (word) values ('focus group');
insert into words (word) values ('complexity');
insert into words (word) values ('Cloned');
insert into words (word) values ('Cloned');
insert into words (word) values ('bandwidth-monitored');
insert into words (word) values ('object-oriented');
insert into words (word) values ('open architecture');
insert into words (word) values ('optimizing');
insert into words (word) values ('local');
insert into words (word) values ('Business-focused');
insert into words (word) values ('Optional');
insert into words (word) values ('system-worthy');
insert into words (word) values ('real-time');
insert into words (word) values ('Decentralized');
insert into words (word) values ('Programmable');
insert into words (word) values ('contingency');
insert into words (word) values ('client-server');
insert into words (word) values ('static');
insert into words (word) values ('Persistent');
insert into words (word) values ('local area network');
insert into words (word) values ('Stand-alone');
insert into words (word) values ('discrete');
insert into words (word) values ('ability');
insert into words (word) values ('systemic');
insert into words (word) values ('Fundamental');
insert into words (word) values ('Optimized');
insert into words (word) values ('Pre-emptive');
insert into words (word) values ('Synergistic');
insert into words (word) values ('Re-contextualized');
insert into words (word) values ('archive');
insert into words (word) values ('forecast');
insert into words (word) values ('Persevering');
insert into words (word) values ('Reactive');
insert into words (word) values ('national');
insert into words (word) values ('mobile');
insert into words (word) values ('composite');
insert into words (word) values ('incremental');
insert into words (word) values ('collaboration');
insert into words (word) values ('Diverse');
insert into words (word) values ('Organized');
insert into words (word) values ('groupware');
insert into words (word) values ('moratorium');
insert into words (word) values ('human-resource');
insert into words (word) values ('uniform');
insert into words (word) values ('hardware');
insert into words (word) values ('incremental');
insert into words (word) values ('Pre-emptive');
insert into words (word) values ('radical');
insert into words (word) values ('archive');
insert into words (word) values ('human-resource');
insert into words (word) values ('Proactive');
insert into words (word) values ('4th generation');
insert into words (word) values ('national');
insert into words (word) values ('Fundamental');
insert into words (word) values ('model');
insert into words (word) values ('Front-line');
insert into words (word) values ('secured line');
insert into words (word) values ('Customer-focused');
insert into words (word) values ('full-range');
insert into words (word) values ('global');
insert into words (word) values ('system-worthy');
insert into words (word) values ('systematic');
insert into words (word) values ('De-engineered');
insert into words (word) values ('model');
insert into words (word) values ('Multi-channelled');
insert into words (word) values ('Graphical User Interface');
insert into words (word) values ('Re-contextualized');
insert into words (word) values ('open architecture');
insert into words (word) values ('Team-oriented');
insert into words (word) values ('Cloned');
insert into words (word) values ('leading edge');
insert into words (word) values ('Re-engineered');
insert into words (word) values ('database');
insert into words (word) values ('empowering');
insert into words (word) values ('cohesive');
insert into words (word) values ('Customer-focused');
insert into words (word) values ('definition');
insert into words (word) values ('mobile');
insert into words (word) values ('portal');
insert into words (word) values ('website');
insert into words (word) values ('definition');
insert into words (word) values ('mission-critical');
insert into words (word) values ('conglomeration');
insert into words (word) values ('database');
insert into words (word) values ('moratorium');
insert into words (word) values ('secondary');
insert into words (word) values ('tertiary');
insert into words (word) values ('Distributed');
insert into words (word) values ('actuating');
insert into words (word) values ('Self-enabling');
insert into words (word) values ('Enhanced');
insert into words (word) values ('dedicated');
insert into words (word) values ('Assimilated');
insert into words (word) values ('Diverse');
insert into words (word) values ('non-volatile');
insert into words (word) values ('intranet');
insert into words (word) values ('uniform');
insert into words (word) values ('capacity');
insert into words (word) values ('paradigm');
insert into words (word) values ('modular');
insert into words (word) values ('analyzing');
insert into words (word) values ('Implemented');
insert into words (word) values ('definition');
insert into words (word) values ('superstructure');
insert into words (word) values ('Implemented');
insert into words (word) values ('analyzer');
insert into words (word) values ('multi-state');
insert into words (word) values ('attitude');
insert into words (word) values ('Cross-group');
insert into words (word) values ('Centralized');
insert into words (word) values ('3rd generation');
insert into words (word) values ('non-volatile');
insert into words (word) values ('fault-tolerant');
insert into words (word) values ('radical');
insert into words (word) values ('Synergistic');
insert into words (word) values ('heuristic');
insert into words (word) values ('system-worthy');
insert into words (word) values ('Graphical User Interface');
insert into words (word) values ('dynamic');
insert into words (word) values ('Inverse');
insert into words (word) values ('next generation');
insert into words (word) values ('radical');
insert into words (word) values ('Realigned');
insert into words (word) values ('system engine');
insert into words (word) values ('User-centric');
insert into words (word) values ('throughput');
insert into words (word) values ('Robust');
insert into words (word) values ('algorithm');
insert into words (word) values ('tangible');
insert into words (word) values ('algorithm');
insert into words (word) values ('benchmark');
insert into words (word) values ('Distributed');
insert into words (word) values ('web-enabled');
insert into words (word) values ('solution');
insert into words (word) values ('pricing structure');
insert into words (word) values ('moderator');
insert into words (word) values ('help-desk');
insert into words (word) values ('leading edge');
insert into words (word) values ('Distributed');
insert into words (word) values ('value-added');
insert into words (word) values ('Open-source');
insert into words (word) values ('Proactive');
insert into words (word) values ('Configurable');
insert into words (word) values ('context-sensitive');
insert into words (word) values ('Managed');
insert into words (word) values ('actuating');
insert into words (word) values ('Polarised');
insert into words (word) values ('Implemented');
insert into words (word) values ('knowledge base');
insert into words (word) values ('Digitized');
insert into words (word) values ('complexity');
insert into words (word) values ('well-modulated');
insert into words (word) values ('explicit');
insert into words (word) values ('next generation');
insert into words (word) values ('matrix');
insert into words (word) values ('Programmable');
insert into words (word) values ('Adaptive');
insert into words (word) values ('bandwidth-monitored');
insert into words (word) values ('contextually-based');
insert into words (word) values ('internet solution');
insert into words (word) values ('conglomeration');
insert into words (word) values ('encoding');
insert into words (word) values ('complexity');
insert into words (word) values ('policy');
insert into words (word) values ('Configurable');
insert into words (word) values ('Distributed');
insert into words (word) values ('incremental');
insert into words (word) values ('executive');
insert into words (word) values ('Total');
insert into words (word) values ('structure');
insert into words (word) values ('disintermediate');
insert into words (word) values ('bi-directional');
insert into words (word) values ('concept');
insert into words (word) values ('Automated');
insert into words (word) values ('6th generation');
insert into words (word) values ('real-time');
insert into words (word) values ('executive');
insert into words (word) values ('asynchronous');
insert into words (word) values ('capability');